### ISSUE TITLE
Unable to run the script on windows

### ISSUE THREAD

**Issue by nitinmukesh** [vishalv26/covid-vaccine-booking#11]
D:\covid>pip install -r requirements.txt
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 2.0 MB/s
Collecting tabulate
  Downloading tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting inputimeout
  Downloading inputimeout-1.0.4-py3-none-any.whl (4.6 kB)
Collecting svglib==1.0.1
  Downloading svglib-1.0.1.tar.gz (900 kB)
     |████████████████████████████████| 900 kB 3.2 MB/s
Collecting reportlab
  Downloading reportlab-3.5.67-cp39-cp39-win_amd64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 6.4 MB/s
Collecting pysimplegui
  Downloading PySimpleGUI-4.43.0-py3-none-any.whl (350 kB)
     |████████████████████████████████| 350 kB 6.8 MB/s
Collecting fake_useragent
  Downloading fake-useragent-0.1.11.tar.gz (13 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 6.4 MB/s
Collecting pyjwt
  Downloading PyJWT-2.1.0-py3-none-any.whl (16 kB)
Collecting lxml
  Downloading lxml-4.6.3-cp39-cp39-win_amd64.whl (3.5 MB)
     |████████████████████████████████| 3.5 MB 6.4 MB/s
Collecting tinycss2>=0.6.0
  Downloading tinycss2-1.1.0-py3-none-any.whl (21 kB)
Collecting cssselect2>=0.2.0
  Downloading cssselect2-0.4.1-py3-none-any.whl (13 kB)
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting soupsieve>1.2
  Downloading soupsieve-2.2.1-py3-none-any.whl (33 kB)
Collecting pillow>=4.0.0
  Downloading Pillow-8.2.0-cp39-cp39-win_amd64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 6.4 MB/s
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 6.8 MB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 6.4 MB/s
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 6.4 MB/s
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 2.9 MB/s
Using legacy 'setup.py install' for svglib, since package 'wheel' is not installed.
Using legacy 'setup.py install' for fake-useragent, since package 'wheel' is not installed.
Installing collected packages: webencodings, tinycss2, pillow, urllib3, soupsieve, reportlab, lxml, idna, cssselect2, chardet, certifi, tabulate, svglib, requests, pysimplegui, pyjwt, inputimeout, fake-useragent, beautifulsoup4
  WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'c:\\python39\\Scripts\\chardetect.exe' -> 'c:\\python39\\Scripts\\chardetect.exe.deleteme'

WARNING: You are using pip version 21.0.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.

**Comment by vishalv26** [comment]
This is permission error. please run as administrator and it should work. or just download the zip and run bat file
