### ISSUE TITLE
SSL issue while sending OTP on windows

### ISSUE THREAD

**Issue by meta-hitesh-aylani** [vishalv26/covid-vaccine-booking#12]
Following SSL error occurring when sending OTP request on Windows machine. Previous version was working fine:

HTTPSConnectionPool(host='cdn-api.co-vin.in', port=443): Max retries exceeded with url: /api/v2/auth/generateMobileOTP (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))

**Comment by nikhilrayaprolu** [comment]
I am facing the same issue now

**Comment by vishalv26** [comment]
Strange. Can you please check if last version is working? Also, Which windows are you using win10 or win7? exactly when it stopped working? Update might not be the issue because nothing much is updated.
