### ISSUE TITLE
add option to choose center slots in advanced version

### ISSUE THREAD

**Issue by circuitmamu** [vishalv26/covid-vaccine-booking#15]
give and additional option like in native version have select center.slot and like 1.1, 1.4

if user pre selected those option **y** then user need to choose
if user pre selected those option **n** then bucket logic was perfect

Bcoz bucket logic is problematic when we go through whole district and sometime  center opened is too far from our location

**Comment by vishalv26** [comment]
You can try pin code then. Because if you keep the slot and center selection then it pretty much defeat the purpose of having a fully automated solution.
