### ISSUE TITLE
Issue with booking slot n constant rate limit by cowin

### ISSUE THREAD

**Issue by saihivarkar** [vishalv26/covid-vaccine-booking#17]
Hi. First a big thanks to u for developing this. Helped many under privileged people.
But recently I am encountering this problem. Whenever I try to book slot, it's searches for slot for only 1 min / 15 min... N then I get this message "rate limit by cowin reduce frequency". Again when I add new otp, still it searches for mere 1 min n gets freeze. I have tired with 10,15,20 secs frequency rate but still the problem persist.
Earlier it never used to happen. Please solve this issue!

**Comment by vishalv26** [comment]
This is related to API of Cowin which we cannot control. It is usually observed when there is bulk opening of slots. You might need to increase the timeout to 30+ seconds sometimes

**Comment by saihivarkar** [comment]
Ok, thank you! I will try with a timeout of 30+ sec. But I have observed that increasing time hampers slot booking. As there is a wait time of more than 30 seconds, and during this period, if any slot opens up, it fails to book it as all the slots get booked!
What would you suggest? Until the day before yesterday, everything was working smoothly, and now suddenly this issue has arisen.

**Comment by vishalv26** [comment]
Like I said, it is cowin api which behaves bit weird when more slots are opened. In fact, it happens when you try manually as well.

**Comment by saihivarkar** [comment]
Thank you for guiding me in this issue. And once again thank you for developing this!
