### ISSUE TITLE
stuck at validating OTP 

### ISSUE THREAD

**Issue by rupamcroy** [vishalv26/covid-vaccine-booking#7]
it gets stuck after entering otp. and receive a end point timeout error.

**Comment by vishalv26** [comment]
Please help me with the error screen shot @rupamcroy @saurabhsharmaj

**Comment by saurabhsharmaj** [comment]
![image](https://user-images.githubusercontent.com/7188167/119452935-8a4aea00-bd54-11eb-9ca8-1ae55de97f7b.png)
please fine the screenshot., is there any way we can read top itself from our msgbox.

**Comment by jainrhea** [comment]
Its giving 504 Response while trying to confirm OTP

**Comment by vishalv26** [comment]
We are working on it.

**Comment by saurabhsharmaj** [comment]
![image](https://user-images.githubusercontent.com/7188167/119456788-a5b7f400-bd58-11eb-8756-565a40b0570d.png)
working after this change.

**Comment by vishalv26** [comment]
Fixed.

**Comment by rs1203** [comment]
Need help with final build. It still shows Validating OTP..

**Comment by vishalv26** [comment]
@rs1203 i just tested. Please download the latest release (Version 3.5) from releases and it should work fine

**Comment by rs1203** [comment]
@vishalv26 Thanks. Its working.
