### ISSUE TITLE
Can't setFont(Times-Roman) missing the T1 files?

### ISSUE THREAD

**Issue by pundiramit** [vishalv26/covid-vaccine-booking#8]
Running this script on ubuntu-20.04 fresh install and running into following error:

Captcha Response Code: 200
Can't setFont(Times-Roman) missing the T1 files?
Originally <class 'TypeError'>: makeT1Font() argument 2 must be str, not None

What dependency package am I missing?

**Comment by vishalv26** [comment]
Python version?

**Comment by vishalv26** [comment]
`git clone https://github.com/Distrotech/reportlab.git
cd reportlab
python setup.py install`

Try this

**Comment by pundiramit** [comment]
Done. I'll let you know how it goes. Thank you! Closing the bug for now.
