### ISSUE TITLE
Error while executing python src\covid-vaccine-slot-booking.py command

### ISSUE THREAD

**Issue by melincredo** [vishalv26/covid-vaccine-booking#9]
Hi Vishal,

Since couple of days getting error while running python src\covid-vaccine-slot-booking.py command though .exe file works.

Please resolve if possible

C:\cowin\covid-vaccine-booking-main\covid-vaccine-booking-main>python src\covid-vaccine-slot-booking.py
Traceback (most recent call last):
  File "src\covid-vaccine-slot-booking.py", line 4, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

C:\cowin\covid-vaccine-booking-main\covid-vaccine-booking-main>

**Comment by vishalv26** [comment]
Please download the latest zip from releases and it should work for you out of the box. EXE is not supported for various reasons. If you want to run yourself using python command then you should do `pip install -r requirements.txt`

**Comment by melincredo** [comment]
Done and all sorted.

Thought earlier pip would have been enough but ran pip again and sorted.

Thank you for the assistance.

Installing collected packages: fake-useragent, soupsieve, beautifulsoup4, pyjwt
  Running setup.py install for fake-useragent ... done
Successfully installed beautifulsoup4-4.9.3 fake-useragent-0.1.11 pyjwt-2.1.0 soupsieve-2.2.1
